### ISSUE TITLE
Error- Can not use hook

### ISSUE THREAD

**Issue by debojitkakoti** [weeco/cortex-gateway#1]
I tried to build the project, got the following error

 ```
github.com/weaveworks/common/logging
../../weaveworks/common/logging/logging.go:25:16: cannot use hook (type *promrus.PrometheusHook) as type "github.com/sirupsen/logrus".Hook in argument to "github.com/sirupsen/logrus".AddHook:
	*promrus.PrometheusHook does not implement "github.com/sirupsen/logrus".Hook (wrong type for Fire method)
		have Fire(*"github.com/weaveworks/promrus/vendor/github.com/sirupsen/logrus".Entry) error
		want Fire(*"github.com/sirupsen/logrus".Entry) error
```

**Comment by weeco** [comment]
Hmm seems weird. I'd guess you are using a different version of the supplied dependencies as the image builds just fine. Can you build the docker image? Are you using Go v1.12?

**Comment by debojitkakoti** [comment]
@weeco Yeah correct `go version go1.12.3 darwin/amd64` . But I have got your docker image, that works so no need to build myself. Thanks.
