### ISSUE TITLE
Gateway seems to distribute the load to Distributors unevenly

### ISSUE THREAD

**Issue by cabrinha** [weeco/cortex-gateway#10]
It seems that one or two of our distributor pods are getting an uneven amount of requests. 

![Screen Shot 2021-05-06 at 9 40 13 AM](https://user-images.githubusercontent.com/775203/117350844-e57a7280-ae61-11eb-9ac2-545463ee4e95.png)

**Comment by weeco** [comment]
The cortex gateway is not responsible for any loadbalancing / load distribution at all. This is actually something we want to change because slow distributors / ingesters can have an impact on the whole ingestion part. But at this stage the cortex gateway will just proxy all requests to your target address which usually is a Kubernetes LoadBalancer.

If you want to validate the theory of unbalanced request distribution you should also rather monitor the number of incoming requests rather than interpreting the unbalanced CPU usage.

**Comment by cabrinha** [comment]
> The cortex gateway is not responsible for any loadbalancing / load distribution at all. This is actually something we want to change because slow distributors / ingesters can have an impact on the whole ingestion part. But at this stage the cortex gateway will just proxy all requests to your target address which usually is a Kubernetes LoadBalancer.

yes, we're just pointing the gateway to the distributor service directly.

> If you want to validate the theory of unbalanced request distribution you should also rather monitor the number of incoming requests rather than interpreting the unbalanced CPU usage.

Do you have any specific metrics I could look at here?

We're also experiencing another issue where store-gateway pods will crash due to long / large queries. The way they crash is by experiencing i/o timeouts to memcached -- not sure if thats related.

**Comment by weeco** [comment]
> yes, we're just pointing the gateway to the distributor service directly.

Then it's all on Kubernetes (including your configuration, readiness probes etc) to properly distribute all requests evenly among the distributors. 

> Do you have any specific metrics I could look at here?

I'd just take a look at the /metrics endpoint as exposed by your distributors. I'm pretty sure there are is one or more metrics that count the number of requests (one for request duration and another for request counter by status I assume).

> We're also experiencing another issue where store-gateway

We are still running the old engine that uses BigTable in the back, but we plan to migrate to the blocks storage engine in the second half of this year. I don't think the gateway could cause any issues with the store-gateway, hence the wrong spot to discuss this. However I can tell you that we see sporadic memcached timeouts as well, they haven't caused any issues though. I never figured out where exactly they come from, possibly networking issues which are probably expected here and there with hundreds of thousands requests / second against it.

**Comment by weeco** [comment]
Bryan explained in the Cortex slack where the unbalanced load could come from:

> As far as I can see, cortex-gateway calls distributors over http.
> There is a possible explanation: the Go http library opens a connection to one distributor, then holds it open as long as it has more calls to make.
> Unless the code takes deliberate steps to not re-use that connection, the load distribution will be unbalanced.
> This is described about half-way down the page here: learnk8s.io/kubernetes-long-lived-connections
> Turning off keepalive in the Go config will stop this happening, however the machines will now spend a lot of effort opening and closing TCP connections.
> Weaveworks uses this fancy-pants algorithm: https://github.com/dlespiau/balance

Even though we don't see unbalanced load in our environment, these are some really good hints we should investigate.

**Comment by cabrinha** [comment]
Putting an Ingress between gateway and distributor seems to fix this.
