### ISSUE TITLE
unsupported protocol scheme

### ISSUE THREAD

**Issue by debojitkakoti** [weeco/cortex-gateway#3]
Getting the following error
`12:28:16 http: proxy error: unsupported protocol scheme ""`
when I configured it with prometheus remote_write
Here is the prometheus cofig
```
remote_write:
    - url: http://localhost:8071/api/prom/push
      bearer_token: eyJhbGciOiJ
```

**Comment by tlkamp** [comment]
Hello, I'm also seeing this error. What was the solution?

**Comment by tlkamp** [comment]
For anyone who stumbles across this issue in the future, I specified the protocol for `-gateway.distributor.address` but not `-gateway.query-frontend.address`. The proxy portion of the app doesn't `log` anything so it took me a little while to notice.
