### ISSUE TITLE
Invalid bearer token

### ISSUE THREAD

**Issue by melkosoft** [weeco/cortex-gateway#4]
I used this token in Prometheus config.
using tcpdump checked HTTP headers from prometheus to gateway: 
User-Agent: Prometheus/2.10.0
Content-Length: 8805
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJPbmxpbmUgSldUIEJ1aWxkZXIiLCJpYXQiOjE1NzE4NDg3ODYsImV4cCI6MTYwMzM4NDc5OSwiYXVkIjoid3d3LmV4YW1wbGUuY29tIiwic3ViIjoianJvY2tldEBleGFtcGxlLmNvbSIsIm5hbWUiOiJteV9wcm9tb18wMSJ9.09gkgEpCu9ryGCRc2DolJDNh5gVY7HG8otAIt0XmdFU
but still getting "Invalid bearer token" in response.  Signing key is provided to gateway. What is wrong with y JWT? What gateway is expecting in JWT payload? Is there any debug log flag which will provide more information from gateway?

**Comment by weeco** [comment]
Hey,
it's poorly documented because I did not expect anyone to use the gateway at the moment.

Take a look at these struct tags, which represent the expected payload in the Bearer tokens: https://github.com/weeco/cortex-gateway/blob/master/gateway/tenant.go#L7-L11
